### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by benwilson512** [mneudert/instream#1]
Hey! I know this is experimental, but does it work? If so, is there any chance you could provide some documentation around basic configuration and usage?

Thanks!

**Comment by mneudert** [comment]
Just updated the readme to contain what I would call the "current public interface". Based on mostly hand-written query string with a wrapping DSL (with series models, etc) upcoming.

Limited feature set of database creation/deletion and data writing/reading should be no problem with any of the current influxdb v0.9 release candidates. If you are defining your own `Instream.Query` modules it should not be much work to have more influxdb features available at hand, misusing `Instream.Data.Read` and `Instream.Data.Write` might even open up all the features :D
