### ISSUE TITLE
Query with series like for write ?

### ISSUE THREAD

**Issue by ibizaman** [mneudert/instream#12]
Is there an easy way to do the equivalent of a write with a series but for a query ?
As of now, the two sides are completely dissociated, right?

**Comment by mneudert** [comment]
For now they are completely disassociated, right. But I am building up some sort of query DSL that will look like this:

```elixir
from(MySeriesDefinition)
|> select([ "field_1", "field_2" ])
|> where(%{ tag_1: "value", tag_2: "value" })
|> MyConnection.read()
```

That is at least the rough concept right now.

Something usable should be up in the next days and if you have any ideas how the querying should work you are free to bring anything up for consideration :)

**Comment by ibizaman** [comment]
I must say I am quite new to InfluxDB and even more to elixir macro system. It seems to be what I expected though. :)

**Comment by dokie** [comment]
I like the approach taken here
https://github.com/robconery/moebius
As a suggestion.

**Comment by ibizaman** [comment]
It would be great if there could be some automatic checks. Like columns names for example, based on the series definition.

**Comment by mneudert** [comment]
Along with a the stuff you can already see on master (or above) the plan is also to support returning series structs from a query result.

(closing this so it does not bitrot)
