### ISSUE TITLE
Mix with custom configuration

### ISSUE THREAD

**Issue by ibizaman** [mneudert/instream#13]
How would you add custom configuration keys to the config.exs?

For example I would like to set the database I am talking to by adding a database key like so:

```elixir
config :influxdb, InfluxDB.Connection,
  hosts:  ["localhost"],
  pool:   [max_overflow: 0, size: 1]
  port:   8086,
  scheme: "http",
  write:  Instream.Writer.Line,
  database: "test"
```

But if fails horribly with:

```
  failure on setup_all callback, tests invalidated
     ** (FunctionClauseError) no function clause matching in Regex.match?/2
     stacktrace:
       (elixir) lib/regex.ex:158: Regex.match?(~r/^[a-zA-Z0-9_\-]+$/, nil)
       (instream) lib/instream/validate.ex:13: Instream.Validate.database!/1
       (instream) lib/instream/cluster/database.ex:18: Instream.Cluster.Database.create/2
       test/influxdb_test.exs:7: InfluxDBTest.__ex_unit_setup_all_0/1
       test/influxdb_test.exs:1: InfluxDBTest.__ex_unit__/2
```

**Comment by mneudert** [comment]
Extending the config should be as easy as, well, extending the config. However there is no logic available to automatically detect and use your keys.

So in your case you would still have to access and pass the database name:

```elixir
Application.get_env(:influxdb, InfluxDB.Connection, [])
|> Keyword.get(:database)
|> Instream.Cluster.Database.create()
|> InfluxDB.Connection.execute()
```

Or access it through your connection module (I think that should work too):

```elixir
InfluxDB.Connection.config[:database]
|> Instream.Cluster.Database.create()
|> InfluxDB.Connection.execute()
```

The `config/0` method basically wraps `Application.get_env/3`.

Could that be what you are looking for?

**Comment by ibizaman** [comment]
Sorry there was some confusion here due to the name "database" I used as key name. In fact, I agree with what you said.
What I wanted to say is that I could not add a key-value pair to the config and try to use it like in your examples without breaking the app. It produces the given stacktrace.

**Comment by mneudert** [comment]
Could you post the `setup_all/1` from your test file? I just tested it locally by adding some random keys to the configuration and it went just fine. Perhaps there is just some typo to be discovered.

**Comment by ibizaman** [comment]
I could not reproduce the error. But still, here is how it does *not* work:
```ruby
config :influxdb, InfluxDB.Connection,
  hosts:  ["localhost"],
  pool:   [max_overflow: 0, size: 1]
  port:   8086,
  scheme: "http",
  write:  Instream.Writer.Line,
  my_param: "my_value"

$ Application.get_all_env
[{:port, 6001},
 {WPI.InfluxDB.Connection,
  [hosts: ["localhost"],
   pool: [max_overflow: 0, size: 1],
   port: 8086,
   scheme: "http",
   writer: Instream.Writer.Line,
   my_param: "my_value"]},
 {:included_applications, []},
 {:test_mode, true}
]
```

In fact, the config must be split in two:
```ruby
config :influxdb, InfluxDB.Connection,
  hosts:  ["localhost"],
  pool:   [max_overflow: 0, size: 1]
  port:   8086,
  scheme: "http",
  write:  Instream.Writer.Line,

config :influxdb,
  my_param: "my_value"

$ Application.get_all_env
[{:port, 6001},
 {WPI.InfluxDB.Connection,
  [hosts: ["localhost"],
   pool: [max_overflow: 0, size: 1],
   port: 8086,
   scheme: "http",
   writer: Instream.Writer.Line]},
 {:my_param, "my_value"},
 {:included_applications, []},
 {:test_mode, true}
]
```

**Comment by mneudert** [comment]
Well, I will just close this for now. The configuration you posted works for me. And without the offending piece of code I can do nothing about that...
