### ISSUE TITLE
erlang error: :"function not exported"

### ISSUE THREAD

**Issue by optikfluffel** [mneudert/instream#2]
I just tried to write some sample values but got stuck pretty fast. If I log my points right before putting them into the query they look like this:

```elixir
[debug] points = [%{fields: %{value: 1.1}, name: "a"}, %{fields: %{value: 2.2}, name: "b"}, %{fields: %{value: 3.3}, name: "c"}]
```

but then I only get an error from erlang:

```elixir
[error] GenServer #PID<0.337.0> terminating
Last message: {:execute, %Instream.Query{payload: "{\"points\":[{\"name\":\"a\",\"fields\":{\"value\":1.1}},{\"name\":\"b\",\"fields\":{\"value\":2.2}},{\"name\":\"3\",\"fields\":{\"value\":3.3}}],\"database\":\"dev_db\"}", type: :write}, []}
State: [module: MyApp.Connection, otp_app: :my_app, hosts: ["localhost"], pool: [max_overflow: 0, size: 1], port: 8086, scheme: "http", username: "phoenix", password: "swordfish"]
** (exit) an exception was raised:
    ** (ErlangError) erlang error: :"function not exported"
        (instream) Instream.Pool.Worker.terminate({%Poison.SyntaxError{message: "Unexpected token: p", token: "p"}, [{Poison.Parser, :parse!, 2, [file: 'lib/poison/parser.ex', line: 56]}, {Poison, :decode!, 2, [file: 'lib/poison.ex', line: 83]}, {Instream.Pool.Worker, :handle_call, 3, [file: 'lib/instream/pool/worker.ex', line: 29]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 607]}, {:gen_server, :handle_msg, 5, [file: 'gen_server.erl', line: 639]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 237]}]}, [module: MyApp.Connection, otp_app: :my_app, hosts: ["localhost"], pool: [max_overflow: 0, size: 1], port: 8086, scheme: "http", username: "phoenix", password: "swordfish"])
        (stdlib) gen_server.erl:621: :gen_server.try_terminate/3
        (stdlib) gen_server.erl:787: :gen_server.terminate/7
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
```

I tried to simply follow the usage examples in your `README`, do you know where I went wrong?

**Comment by mneudert** [comment]
Well, the error is not directly an unexported function. There is no real error handling so the workers have no terminate method and result in this misleading message.

The actual error is found in the line starting with `(instream)` (fourth from the bottom). The message looks like the response is not in JSON format so Poison simply fails to decode it.

For a better answer there are 2 things you should check:

1.  Your influxdb version. Only the version in the `.travis.yml` (0.9.0-rc30) is tested. An older or newer release might lead to some weird failures. The official changelog for example mentions a rename of the data key for the measurement name from `name` to `measurement`.
2. You should try to get the raw server response from the using `MyApp.MyConnection.execute([ result_as: :raw ])`.

For starters I would look at the installed influxdb version :)

**Comment by optikfluffel** [comment]
Ah I had `v0.8.8` installed, after upgrading everything worked fine, thanks!
