### ISSUE TITLE
Reading config from environment variables on runtime is not working properly

### ISSUE THREAD

**Issue by techgaun** [mneudert/instream#23]
Hi there,

The config reading from environment variables is not working properly. I had to do some hacky stuff : https://github.com/mneudert/instream/compare/master...techgaun:master but I didn't want to PR as I did it quickly for our use case but wanted to let you know.

**Comment by techgaun** [comment]
I saw that there's a new commit today. I failed to notice it before creating this issue :( . I'll test with new changes and update the issue.

**Comment by mneudert** [comment]
No worries there :)

Before today's commits all environmental access was not supposed to work fully. It was just undocumented preparation work. Had the actual support already lying around some time but didn't come to terms with adding proper tests and that delayed it quite a bit...
