### ISSUE TITLE
Travis testing against matrix of elixir/otp

### ISSUE THREAD

**Issue by h4cc** [mneudert/instream#28]
It would be cool to have the build matrix include different versions for elixir/otp.

Documentation: https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix

**Comment by mneudert** [comment]
Yep, won't hurt 👍 

I added `elixir 1.3.4` and the most recent `elixir 1.4.0-rc.1` to the matrix for testing against `influxdb 1.1.0`. Adding more InfluxDB versions would probably only inflate the build times without much benefit.

Do you know of any good argument for also including different OTP versions?

**Comment by h4cc** [comment]
Regarding OTP versions, everything `>= 18.0` should be abled to run Elixir `>= 1.1`.

A good idea should be the build matrix of credo: https://github.com/rrrene/credo/blob/master/.travis.yml

So the latest Elixir `1.1`, `1.2`, `1.3` and later `1.4` release with OTP `18.0` to `19.1` should be the range you can select from.
In the end it also matters what you want to support with a `v1.0` of this software. Supporting Elixir 1.1 can be hard, but its is the version available in default ubuntu repos for 16.04 LTS (http://packages.ubuntu.com/search?suite=xenial&searchon=names&keywords=elixir).

**Comment by mneudert** [comment]
As poison requires `~> 1.1` to not generate any compiler warning and this library is at `~> 1.2` I think we can safely ignore any problems regarding older versions. Yet Travis would happily set up any version available through `kiex` and `kerl` so it wouldn't even be a problem on that side.

Regarding the OTP version range I am still thinking about whether it would even make any difference which version is used as long as Elixir is compatible. Except for the UDP connection and dependencies (like `hackney`) only Elixir modules are used. And I trust those are good enough to not have any impact on a library.

At least I don't know of any Erlang changes that make a difference.

Adding `Elixir master + most recent OTP` to the matrix might be the interesting choice. Just to catch things like the compiler notices from Elixir `1.4` (parenthesis) in a drive-by fashion.

**Comment by mneudert** [comment]
It's running a while now with a selection of Elixir versions and an additional `OTP 19.0`. While the versions will change the matrix size should be big enough to cover potential failures (and not overload travis too much). It could be extended after all if there is some combination making problems...
