### ISSUE TITLE
Series `database` not optional

### ISSUE THREAD

**Issue by h4cc** [mneudert/instream#29]
I have defined a series without a `database: "some_db"`.
I was expecting that the database i defined in `config.exs` will be taken.
Instead there is a error like `%{error: "database is required"}`.

Is there a way to achieve this?

**Comment by h4cc** [comment]
Found in the README. When not defining a `database` in a series, steps 3 and 4 are skipped:

> 1. opts[:database] parameter
> 2. Series struct (if used)
> 3. Connection configuration
> 4. No database used!

**Comment by h4cc** [comment]
Seems to be fixed already. Was testing with v0.13 where is commit is not included: https://github.com/mneudert/instream/commit/daa714fe57bf4f34b6c5e6d56b88e67930b57089

Having a v0.14 would be cool btw :)

**Comment by mneudert** [comment]
Hm... you are the second person this week to trip over the version mentioned in a README file. Do you know of any simple statement I could include to tell that the version on GitHub may not reflect the actual version fetched from Hex?

Btw, I think a new release should be out next week. I was just delaying everything until I had a nice way to have features tested with a minimum InfluxDB version. As that is done by now I have no reason not to get it out :D

**Comment by h4cc** [comment]
To be honest, ist just read the parts of the README that i needed.
While trying to find the bug myself i stumbled upon that commit.

Maybe releasing more often could help reducing the duration of the feedback loop :)
