### ISSUE TITLE
Crash on write timeout using Instream.Writer.Line and hackney problem

### ISSUE THREAD

**Issue by h4cc** [mneudert/instream#33]
Today we had a connection issue to our InfluxDB and seen some errors like this:

```
** (MatchError) no match of right hand side value: {:error, :connect_timeout}
(instream) lib/instream/writer/line.ex:26: Instream.Writer.Line.write/3
(instream) lib/instream/connection/query_runner.ex:144: anonymous fn/4 in Instream.Connection.QueryRunner.write/3
(stdlib) timer.erl:166: :timer.tc/1
(instream) lib/instream/connection/query_runner.ex:142: Instream.Connection.QueryRunner.write/3
(instream) lib/instream/pool/worker.ex:36: Instream.Pool.Worker.handle_call/3
(stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
(stdlib) gen_server.erl:647: :gen_server.handle_msg/5
(stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:execute, %Instream.Query{method: :get, opts: [database: nil], payload: %{points: [%{fields: %{bandwidth: 125}, measurement: "readings", tags: %{uuid: "847D501619122277"}, timestamp: 1483612556000000000}]}, type: :write}, [database: nil]}
State: %{module: MyApp.Influx.Connection}
=CRASH REPORT==== 5-Jan-2017::10:36:04 ===
crasher:
initial call: Elixir.Instream.Pool.Worker:init/1
pid: <0.28185.4>
registered_name: []
exception exit: {{badmatch,{error,connect_timeout}},
[{'Elixir.Instream.Writer.Line',write,3,
[{file,"lib/instream/writer/line.ex"},{line,26}]},
{'Elixir.Instream.Connection.QueryRunner',
'-write/3-fun-0-',4,
[{file,"lib/instream/connection/query_runner.ex"},
{line,144}]},
{timer,tc,1,[{file,"timer.erl"},{line,166}]},
{'Elixir.Instream.Connection.QueryRunner',write,3,
[{file,"lib/instream/connection/query_runner.ex"},
{line,142}]},
{'Elixir.Instream.Pool.Worker',handle_call,3,
[{file,"lib/instream/pool/worker.ex"},{line,36}]},
{gen_server,try_handle_call,4,
[{file,"gen_server.erl"},{line,615}]},
{gen_server,handle_msg,5,
[{file,"gen_server.erl"},{line,647}]},
{proc_lib,init_p_do_apply,3,
[{file,"proc_lib.erl"},{line,247}]}]}
in function gen_server:terminate/7 (gen_server.erl, line 812)
ancestors: [<0.1659.0>,'Elixir.MyApp.Influx.Connection.Pool',
'Elixir.MyApp.Supervisor',<0.1528.0>]
messages: []
links: [<0.1658.0>,<0.1659.0>]
dictionary: []
trap_exit: false
status: running
heap_size: 2586
stack_size: 27
reductions: 4045
[error] GenServer #PID<0.28185.4> terminating
{shutdown,5000},
Supervisor: {<0.1659.0>,poolboy_sup}
Context: child_terminated
Reason: {{badmatch,{error,connect_timeout}},
```

The part of the implementation of `Instream.Writer.Line` looks like this:

```
    { :ok, status, headers, client } = :hackney.post(url, headers, body, http_opts)
    { :ok, response }                = :hackney.body(client)
```

I would like to handle the error other than crashing.

Could the `Instream.Writer.Line` be changed, so it will not crash on `{:error, _}` ?
Also giving that `:error` up to the call of `Connection.write` ?

--------------------------------

What i also discovered, is that after all workers from Instream have crashed, also any other calls using hackney failed. Could that be connected?

**Comment by mneudert** [comment]
Yeah, that behavior could of course be changed to log a message and returning an error tuple instead of simply crashing the pool workers. (For a quick change you could simply replace the writer with your own flavor)

Unless `poolboy` gives up on restarting the workers the calls should eventually work again just fine. And as there is no special configuration for `hackney` the default pool there should also stay working. If anything completely broke there should probably be errors mentioning a missing/unknown process.

Or did another application using `hackney` also stop working?

**Comment by mneudert** [comment]
I actually intended to modify the current behavior using "bang-style" methods at some point. So one is given the choice of crashing/raising or returning error tuples...

**Comment by h4cc** [comment]
I had quite some stuff using hackney that stopped too, they ware using the default pool, which i will change asap now :)

Being abled to define a custom hackney pool for Instream would be a good start. Thanks.

**Comment by mneudert** [comment]
I will try to find a way to make that work.

Until then I can only suspect that the clients receiving an error have not been cleaned up by hackney. Up to the point hackney had nothing left in its pool and silently stopped working. Have the other applications received timeouts reaching out to hackney or was is something not that obvious?

**Comment by mneudert** [comment]
I have to stand partially corrected.

You should already be able to change the default pool using the `:http_opts` configuration for your connection:

```elixir
config MyApp, MyApp.MyConnection,
  http_opts: [ pool: :my_custom_pool ]
```

After at least one call using that connection the pool should be automatically started by hackney. The pool configuration will be taken from the `:http_opts` configuration allowing you to customize `:max_connections` and other values for hackney.

```elixir
iex> :ets.lookup(:hackney_pool, :my_custom_pool)
[my_custom_pool: #PID<0.177.0>]
```

**Comment by h4cc** [comment]
That is a good hint, will try that out on next deployment. Thanks!

**Comment by mneudert** [comment]
With the last change every error from hackney should be forwarded to the caller without crashing a process. And therefore make it possible to actually handle the errors. Hopefully that also solves the any issues with the hackney pool (while using a seperate pool is of course still a good choice).
