### ISSUE TITLE
Issue with distillery

### ISSUE THREAD

**Issue by laibulle** [mneudert/instream#45]
Hello, when I use instream with distillery, I get an error
```
** (Protocol.UndefinedError) protocol Enumerable not implemented for {GenServer, :call, [#PID<11160.2205.0>, {:execute, %Instream.Query{method: :get, opts: [host: nil], payload: nil, type: :ping}, [log: false]}, :infinity]}
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:2979: Enum.map_join/3
    (elixir) lib/exception.ex:572: Exception.format_stacktrace/1
    (elixir) lib/exception.ex:145: Exception.format/3
    (distillery) lib/mix/lib/releases/runtime/control.ex:643: Mix.Releases.Runtime.Control.rpc/2
    (distillery) lib/entry.ex:44: Mix.Releases.Runtime.Control.main/1
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
```

when I run 

```
./bin/bonsai rpc 'Bonsai.InfluxConnection.ping(log: false) '
```

It is quite difficult to find what's wrong. Any idea ?

**Comment by mneudert** [comment]
The code of distillery hints at some `{:badrpc, {:EXIT, {type, trace}}}` error (see [here](https://github.com/bitwalker/distillery/blob/master/lib/mix/lib/releases/runtime/control.ex#L637)).

Can you check with an RPC call if the connection configuration is correct? Something like `Bonsai.InfluxConnection.config()` should return it. Perhaps it is just some configuration issue.

**Comment by laibulle** [comment]
Actually, the connection was not correct, it is fixed now. But it was quite impossible to see what's wrong with this error message.
