### ISSUE TITLE
support for mix release

### ISSUE THREAD

**Issue by sandromehic** [mneudert/instream#53]
Hi there, I'm using instream with 1.9 elixir and when trying to create release with `mix release`, I get the error since `:influxql` is in the included_applications. Here is the error message:

```
** (Mix) Undefined applications: [influxql]
```
Simply removing `included_applications` from `mix.exs` solves the issue, and it works perfectly, but I'm not sure if it breaks the library on older versions of Elixir (i believe prior to 1.6 or 1.5, it was necessary to define other applications that you want started by the BEAM). For now I have my own fork with this modification. If you think this change is something you would like to include, I can PR it.

Of course, if there is a different way to solve this issue, let me know.

P.S. Thanks for the work put in to this project, appreciate it!

**Comment by mneudert** [comment]
I suppose you are using Elixir `1.9.0` to create your release, right?

The combination of `mix release` and `:included_applications` only works from `1.9.1` onwards. If you cannot update your Elixir release it should also work to add `:influxql` to your top application's `:extra_applications` list as a workaround.

_I will most likely just remove the `:included_applications` as a permanent fix as there is no Elixir release marked as supported anymore that does not have the automatic application inference (added in `1.4.0` ^^)._

**Comment by sandromehic** [comment]
Right on point! I updated my elixir version on target system to `1.9.4` and it works like a charm. I was not aware of this bug in `1.9.0`, sorry for creating an issue here.

Maybe the best way to proceed is to just remove it from `:included_applications` as you mentioned, instead of complicating the documentation to explain that release won't work with `1.9.0`.

Anyway, feel free to close the issue. Thanks again!
