### ISSUE TITLE
InfluxDB 2.x and InfluxDB Cloud Support

### ISSUE THREAD

**Issue by sheldonkreger** [mneudert/instream#58]
I am configuring monitoring for an Elixir application and plan to use InfluxDB Cloud to store my metric data. It is recommended to use their new service, which only supports InfluxDB 2.x. The configuration for their cloud product uses token based authentication, which doesn't appear to be possible in the current version. There are probably other compatibility issues which I am not aware of.

Just wondering if there are plans to support 2.x and/or InfluxDB cloud. I know their company is committed to supporting the BEAM ecosystem, so I will probably reach out to them directly if there isn't work being done already. Thank you.

**Comment by mneudert** [comment]
Currently there are only vague plans to fully support InfluxDB 2.x (initially using the compatibility layer introduced with 1.8) as it requires quite some changes or a maybe even a complete cut (supporting only one of the two).

Using the library at the moment for a version 2 endpoint will most likely not work in any meaningful way. For example writing data requires a writer modification to support the new endpoint URLs (the format of the data seems to be the same, so mostly URL construction and replacing the Basic Auth header with a configurable token value). The response values from Flux queries will also only be available in a raw format as there is no way to have them parsed at the moment.

**Comment by sheldonkreger** [comment]
Thank you for the information. I will keep my eye on this library, but will probably use something else for now because I need the 2.x support for the InfluxDB cloud service.
