### ISSUE TITLE
New release (0.23)

### ISSUE THREAD

**Issue by agramichael** [mneudert/instream#59]
Any timeline for when there will be a new release? 

There has been plenty of work done since 0.22. I am currently using the repo's master branch as a dependency because 0.22 has outdated dependencies that won't work in our project.

**Comment by mneudert** [comment]
Not a real timeline, sorry. From a feature standpoint the only changes to be made before a release is a rework of the documentation. Mostly by inlining the documentation into the appropriate modules and updating to reflect the changes done. So while I can not give any date I would say it should, once released, behave exactly like the branch you are currently using.

Having an issue open asking for a release however has always helped in getting the necessary motivation to finally get those things done :)
