### ISSUE TITLE
2.0 Support timeframe

### ISSUE THREAD

**Issue by unozerocode** [mneudert/instream#60]
Hi, 

What is the timeframe for incorporating support for Influx 2.0?

**Comment by mneudert** [comment]
There is no timeframe at the moment except some sort of "eventually", sorry.

**Comment by unozerocode** [comment]
That´s ok, thanks for your response. We have just had a lot of connectivity issues, we have tried pretty much every library, even Postman, and they all fail with some variant of "socket closed remotely".  The way it seems to break compatibility from 1.8 to 2.0 is strange for something with a simple REST API. I think we will give up on Influx, even though it looks beautiful, something seems to be wrong with the way they are handling http connections, because it shouldn´t be this difficult to push data into it.
