### ISSUE TITLE
Add ability to write explicit timestamps to series

### ISSUE THREAD

**Issue by jamesotron** [mneudert/instream#7]
The system I'm measuring generates usec timestamps with it's events, so I need to push them to influx along with the tags and fields. I'll start hacking on a PR to add it, but let me know if I need to know anything in particular.

**Comment by mneudert** [comment]
If you are using the JSON writer it should already be possible. Well, "akwardly creating the raw json payload by hand"-possible. That one should probably work without touching anything.

However the line writer should become the default one before long (like, end of the week) and that needs the work. Adding a field `:timestamp` to Instream.Series (just like `:measurement` or `:database`, but without having to define it in the series definition) should be the most suitable way to achieve what you need.

**Comment by jamesotron** [comment]
The JSON writer doesn't even work for me, on InfluxDB 0.9.4.1.  I'll look at adding it to the Line protocol writer. Thanks :+1:

**Comment by mneudert** [comment]
Closing in favor of the PR.
