### ISSUE TITLE
Add a from_pivot on series struct

### ISSUE THREAD

**Issue by Ma233** [mneudert/instream#71]
With flux in influxdb 2.0, the way to load a row of measurements has been changed. (Ref: https://www.influxdata.com/blog/how-to-pivot-data-flux-columnar-data/)

And the result of pivot is not compatible with `from_map` and `from_result`.
Maybe we can add a `from_pivot` for this? Or can we upgrade `from_map` and `from_result` to load them?

@mneudert I have a passion for implementing this feature. Could you please give me some advice?

**Comment by mneudert** [comment]
I would say please go ahead and upgrade `from_result` :+1:

Looking at the example results in the blog entry you linked it should fit in there nicely if you treat `_field` and `_value` as optional.
