### ISSUE TITLE
Influx DB Cloud access returns an error

### ISSUE THREAD

**Issue by kuffel** [mneudert/instream#76]
We are trying to access an Cloud Influx DB 2.4 instance.

Querying the data with:

`
MyService.Connection.query("from(bucket: "some_bucket") |> range(start: -24h) |> first()", log: true)
`

Results in:

`
%{code: "invalid", message: "invalid: unsupported Content-Type header value"}
`

We are using the latest master of instream and this configuration.

```
config :my_service, MyService.Connection,
   auth: [
     method: :token,
     token: "SOME_TOKEN"
   ],
   bucket: "some_bucket",
   org: "some_org",
   scheme: "https",
   host: "westeurope-1.azure.cloud2.influxdata.com",
   port: 443,
   http_opts: [recv_timeout: 30_000],
   version: :v2
```

Any idea how to solve this issue?

**Comment by kuffel** [comment]
The issue can be solved by adding an the option: "query_language: :flux" to the query call.

**Comment by mneudert** [comment]
Well, as I learned just now sending no `Content-Type` header at all seems to only work for self hosted instances :grimacing: 

Could you verify the linked PR solves this problem without having to manually set the language options?

**Comment by kuffel** [comment]
Yes it does fix the issue. Thanks for the very quick fix.

**Comment by mneudert** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
